# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tumbleweed Technology
email: contact@schroederspace.com
description: > # this means to ignore newlines until "baseurl:"
  The random nonsensical musings of a professional software enginneer 
  that will most likely be read by absolutely noone.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.schroederspace.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  jpschroeder

# Build settings
markdown: kramdown
